version: '3.5'

services:
  laravel-app:
    build:
      context: '.'
      args:
        uid: ${UID}
    container_name: laravel-app
    environment:
    - APACHE_RUN_USER=#${UID}
    - APACHE_RUN_GROUP=#${UID}
    volumes:
    - .:/var/www/html
    ports:
    - 8000:80
    networks:
      backend:
        aliases:
        - laravel-app

  mysql-db:
    image: mysql:5.7
    container_name: mysql-db
    volumes:
    - ./run/var:/var/lib/mysql
    environment:
    - MYSQL_ROOT_PASSWORD=1234
    - MYSQL_DATABASE=shop_online
    - MYSQL_USER=user
    - MYSQL_PASSWORD=1234
    ports:
    - 3306:3306
    networks:
      backend:
        aliases:
        - db

networks:
  backend:
    name: backend-network